apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hzv8myakr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hzv8myakr-go 
  name: hzv8myakr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hzv8myakr-go 
